### ISSUE TITLE
[Bug]: dark/light with system mode 

### ISSUE THREAD

**Issue by Tayebsed93** [Orange-OpenSource/ods-flutter#176]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-flutter/issues) for duplicate or closed feature requests

### Your test device

iphone 13 pro

### OS Version

iOS 16.1

### App version

v1.0.0

### Describe the issue

the light / dark mode is changed only with the button

### Expected Behavior

the light dark appearance must adapt according to the system setting

**Comment by B3nz01d** [comment]
The current behavior is that the app opens at the default OS state, then when using the app bar action icon this action toggles between:
* default OS mode
* light mode
* dark mode
* light mode dark mode
* ...

As a target the icon should switch between 3 states:
* default OS mode
* light mode
* dark mode
* default OS mode
* light mode
* dark mode
* ...

In order to perform that switch you need to use another icon. 
@mccart77: need to define the corresponding icon

inspiration idea: 
* idea 1: use the existing sun and moon to be used half half as in the example of the encryption icon
* idea 2: use the solar energy direction and find a center symbol to express automation  

I'm proposing to use this one until we have the definitive one: ic_data

**Comment by B3nz01d** [comment]
After review with Design:
when launching use the app the default setup is set to "auto"

The icon shown at a certain point is the current state icon.

The display to the user is a drop down that allows to see all 3 available choices:
* light
* dark
* auto
